### PR TITLE
Fix option->options

### PR DESCRIPTION
**Pull request by giovannipizzi**
There were, I think, a few typos.

### CODE REVIEW

**Comment by giovannipizzi** [comment]
Also, at least in my case, following the example
```python
metadata={
            'options': {
                'prepend_text': 'conda activate some-conda-env'
            }
```
starts asking also for resources; just putting `resources={}` works, but adding the `submit_script_filename` then requires `resources': {'tot_num_mpiprocs': 1}`. 
Not sure if this is intended (then one should explain in various points in the docs), or it's a bug (and an issue should be opened?)

**Comment by sphuber** [comment]
> Also, at least in my case, following the example
> 
> ```python
> metadata={
>             'options': {
>                 'prepend_text': 'conda activate some-conda-env'
>             }
> ```
> 
> starts asking also for resources; just putting `resources={}` works, but adding the `submit_script_filename` then requires `resources': {'tot_num_mpiprocs': 1}`. Not sure if this is intended (then one should explain in various points in the docs), or it's a bug (and an issue should be opened?)

That is weird. Are you sure the problem _only_ arises when you specify `metadata`? Are you using `launch_shell_job` or launching a `ShellJob` directly?

What `computer` is being used? What scheduler does that use and does it define the `default_mpiprocs_per_machine` value? My guess is that the latter is not defined, and so the resources are underfined for most scheduler types. So it may just be an edge case where you set the `localhost` computer up before you started using `aiida-shell` and didn't define the default MPI procs per machine

**Comment by sphuber** [comment]
If the analysis is correct, I could add a check in `launch_shell_job` to make sure that `default_mpiprocs_per_machine` is defined, and if not either raise an exception/warning, or simply automatically set it to 1.

**Comment by sphuber** [comment]
Thanks for the PR @giovannipizzi

**Comment by giovannipizzi** [comment]
Yes, I am trying to run with sqlite and no rmq, and the computer was setup with

```
verdi computer setup -L localhost -H localhost -T core.local -S core.direct -w `echo $PWD/work` -n
verdi computer configure core.local localhost --safe-interval 1 -n
```

**Pull request merged**
